### ISSUE TITLE
Replace Lorem Ipsem with content

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/urlShortner#104] opened 2020-10-02 15:57 UTC
We need concrete content here

**Comment by bughunter9** [comment] 2020-10-02 17:00
@shubhank-saxena  @jsparmani  Can I write the content for this ??

**Comment by shubhank-saxena** [comment] 2020-10-02 17:04
@bughunter9 I did merge one the PRs which suggested some changes. Feel free to put up a PR if you feel we can have better content!

**Comment by bughunter9** [comment] 2020-10-02 17:09
On it :)

**Comment by SabhyaGrover** [comment] 2020-10-02 18:41
Duplicate of #70

**Closed by SabhyaGrover** 2020-10-02 18:41 UTC
Labels: duplicate, enhancement, frontend
